# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

upstream mqtt_ws_cluster {
    server fluxmq-node1:${SMQ_FLUXMQ_WS_PORT};
    server fluxmq-node2:${SMQ_FLUXMQ_WS_PORT};
    server fluxmq-node3:${SMQ_FLUXMQ_WS_PORT};
}
