# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

with-expecter: true
filename: "{{.InterfaceName}}.go"
outpkg: "mocks"
boilerplate-file: "./tools/config/boilerplate.txt"
packages:
  github.com/absmach/supermq/internal/grpc/things/v1:
    interfaces:
      ThingsServiceClient:
        config:
          dir: "./things/mocks"
          mockname: "ThingsServiceClient"
          filename: "things_client.go"
  github.com/absmach/supermq/internal/grpc/domains/v1:
    interfaces:
      DomainsServiceClient:
        config:
          dir: "./domains/mocks"
          mockname: "DomainsServiceClient"
          filename: "domains_client.go"
  github.com/absmach/supermq/internal/grpc/token/v1:
    interfaces:
      TokenServiceClient:
        config:
          dir: "./auth/mocks"
          mockname: "TokenServiceClient"
          filename: "token_client.go"
  github.com/absmach/supermq/internal/grpc/channels/v1:
    interfaces:
      ChannelsServiceClient:
        config:
          dir: "./channels/mocks"
          mockname: "ChannelsServiceClient"
          filename: "channels_client.go"
  github.com/absmach/supermq/internal/grpc/groups/v1:
    interfaces:
      GroupsServiceClient:
        config:
          dir: "./groups/mocks"
          mockname: "GroupsServiceClient"
          filename: "groups_client.go"

  github.com/absmach/supermq/certs/pki/amcerts:
    interfaces:
      Agent:
        config:
          dir: "./certs/mocks"
          mockname: "Agent"
          filename: "pki.go"
