# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'supermq'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    follow_redirects: true
    enable_http2: true
    static_configs:
    - targets: 
      - supermq-auth:9001
      - supermq-users:9002
      - supermq-domains:9003
      - supermq-groups:9004
      - supermq-channels:9005
      - supermq-clients:9006
      - supermq-journal:9021
