// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/absmach/supermq/pkg/oauth2"
	mock "github.com/stretchr/testify/mock"
)

// NewDeviceCodeStore creates a new instance of DeviceCodeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceCodeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceCodeStore {
	mock := &DeviceCodeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DeviceCodeStore is an autogenerated mock type for the DeviceCodeStore type
type DeviceCodeStore struct {
	mock.Mock
}

type DeviceCodeStore_Expecter struct {
	mock *mock.Mock
}

func (_m *DeviceCodeStore) EXPECT() *DeviceCodeStore_Expecter {
	return &DeviceCodeStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type DeviceCodeStore
func (_mock *DeviceCodeStore) Delete(deviceCode string) error {
	ret := _mock.Called(deviceCode)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(deviceCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DeviceCodeStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type DeviceCodeStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - deviceCode string
func (_e *DeviceCodeStore_Expecter) Delete(deviceCode interface{}) *DeviceCodeStore_Delete_Call {
	return &DeviceCodeStore_Delete_Call{Call: _e.mock.On("Delete", deviceCode)}
}

func (_c *DeviceCodeStore_Delete_Call) Run(run func(deviceCode string)) *DeviceCodeStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DeviceCodeStore_Delete_Call) Return(err error) *DeviceCodeStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DeviceCodeStore_Delete_Call) RunAndReturn(run func(deviceCode string) error) *DeviceCodeStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type DeviceCodeStore
func (_mock *DeviceCodeStore) Get(deviceCode string) (oauth2.DeviceCode, error) {
	ret := _mock.Called(deviceCode)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 oauth2.DeviceCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (oauth2.DeviceCode, error)); ok {
		return returnFunc(deviceCode)
	}
	if returnFunc, ok := ret.Get(0).(func(string) oauth2.DeviceCode); ok {
		r0 = returnFunc(deviceCode)
	} else {
		r0 = ret.Get(0).(oauth2.DeviceCode)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(deviceCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DeviceCodeStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type DeviceCodeStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - deviceCode string
func (_e *DeviceCodeStore_Expecter) Get(deviceCode interface{}) *DeviceCodeStore_Get_Call {
	return &DeviceCodeStore_Get_Call{Call: _e.mock.On("Get", deviceCode)}
}

func (_c *DeviceCodeStore_Get_Call) Run(run func(deviceCode string)) *DeviceCodeStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DeviceCodeStore_Get_Call) Return(deviceCode1 oauth2.DeviceCode, err error) *DeviceCodeStore_Get_Call {
	_c.Call.Return(deviceCode1, err)
	return _c
}

func (_c *DeviceCodeStore_Get_Call) RunAndReturn(run func(deviceCode string) (oauth2.DeviceCode, error)) *DeviceCodeStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserCode provides a mock function for the type DeviceCodeStore
func (_mock *DeviceCodeStore) GetByUserCode(userCode string) (oauth2.DeviceCode, error) {
	ret := _mock.Called(userCode)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserCode")
	}

	var r0 oauth2.DeviceCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (oauth2.DeviceCode, error)); ok {
		return returnFunc(userCode)
	}
	if returnFunc, ok := ret.Get(0).(func(string) oauth2.DeviceCode); ok {
		r0 = returnFunc(userCode)
	} else {
		r0 = ret.Get(0).(oauth2.DeviceCode)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DeviceCodeStore_GetByUserCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserCode'
type DeviceCodeStore_GetByUserCode_Call struct {
	*mock.Call
}

// GetByUserCode is a helper method to define mock.On call
//   - userCode string
func (_e *DeviceCodeStore_Expecter) GetByUserCode(userCode interface{}) *DeviceCodeStore_GetByUserCode_Call {
	return &DeviceCodeStore_GetByUserCode_Call{Call: _e.mock.On("GetByUserCode", userCode)}
}

func (_c *DeviceCodeStore_GetByUserCode_Call) Run(run func(userCode string)) *DeviceCodeStore_GetByUserCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DeviceCodeStore_GetByUserCode_Call) Return(deviceCode oauth2.DeviceCode, err error) *DeviceCodeStore_GetByUserCode_Call {
	_c.Call.Return(deviceCode, err)
	return _c
}

func (_c *DeviceCodeStore_GetByUserCode_Call) RunAndReturn(run func(userCode string) (oauth2.DeviceCode, error)) *DeviceCodeStore_GetByUserCode_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type DeviceCodeStore
func (_mock *DeviceCodeStore) Save(code oauth2.DeviceCode) error {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(oauth2.DeviceCode) error); ok {
		r0 = returnFunc(code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DeviceCodeStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type DeviceCodeStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - code oauth2.DeviceCode
func (_e *DeviceCodeStore_Expecter) Save(code interface{}) *DeviceCodeStore_Save_Call {
	return &DeviceCodeStore_Save_Call{Call: _e.mock.On("Save", code)}
}

func (_c *DeviceCodeStore_Save_Call) Run(run func(code oauth2.DeviceCode)) *DeviceCodeStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 oauth2.DeviceCode
		if args[0] != nil {
			arg0 = args[0].(oauth2.DeviceCode)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DeviceCodeStore_Save_Call) Return(err error) *DeviceCodeStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DeviceCodeStore_Save_Call) RunAndReturn(run func(code oauth2.DeviceCode) error) *DeviceCodeStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type DeviceCodeStore
func (_mock *DeviceCodeStore) Update(code oauth2.DeviceCode) error {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(oauth2.DeviceCode) error); ok {
		r0 = returnFunc(code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DeviceCodeStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type DeviceCodeStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - code oauth2.DeviceCode
func (_e *DeviceCodeStore_Expecter) Update(code interface{}) *DeviceCodeStore_Update_Call {
	return &DeviceCodeStore_Update_Call{Call: _e.mock.On("Update", code)}
}

func (_c *DeviceCodeStore_Update_Call) Run(run func(code oauth2.DeviceCode)) *DeviceCodeStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 oauth2.DeviceCode
		if args[0] != nil {
			arg0 = args[0].(oauth2.DeviceCode)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DeviceCodeStore_Update_Call) Return(err error) *DeviceCodeStore_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DeviceCodeStore_Update_Call) RunAndReturn(run func(code oauth2.DeviceCode) error) *DeviceCodeStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
