// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/absmach/supermq/api/grpc/token/v1"
	"github.com/absmach/supermq/pkg/oauth2"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreateDeviceCode provides a mock function for the type Service
func (_mock *Service) CreateDeviceCode(ctx context.Context, provider oauth2.Provider, verificationURI string) (oauth2.DeviceCode, error) {
	ret := _mock.Called(ctx, provider, verificationURI)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeviceCode")
	}

	var r0 oauth2.DeviceCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth2.Provider, string) (oauth2.DeviceCode, error)); ok {
		return returnFunc(ctx, provider, verificationURI)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth2.Provider, string) oauth2.DeviceCode); ok {
		r0 = returnFunc(ctx, provider, verificationURI)
	} else {
		r0 = ret.Get(0).(oauth2.DeviceCode)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oauth2.Provider, string) error); ok {
		r1 = returnFunc(ctx, provider, verificationURI)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_CreateDeviceCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDeviceCode'
type Service_CreateDeviceCode_Call struct {
	*mock.Call
}

// CreateDeviceCode is a helper method to define mock.On call
//   - ctx context.Context
//   - provider oauth2.Provider
//   - verificationURI string
func (_e *Service_Expecter) CreateDeviceCode(ctx interface{}, provider interface{}, verificationURI interface{}) *Service_CreateDeviceCode_Call {
	return &Service_CreateDeviceCode_Call{Call: _e.mock.On("CreateDeviceCode", ctx, provider, verificationURI)}
}

func (_c *Service_CreateDeviceCode_Call) Run(run func(ctx context.Context, provider oauth2.Provider, verificationURI string)) *Service_CreateDeviceCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oauth2.Provider
		if args[1] != nil {
			arg1 = args[1].(oauth2.Provider)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_CreateDeviceCode_Call) Return(deviceCode oauth2.DeviceCode, err error) *Service_CreateDeviceCode_Call {
	_c.Call.Return(deviceCode, err)
	return _c
}

func (_c *Service_CreateDeviceCode_Call) RunAndReturn(run func(ctx context.Context, provider oauth2.Provider, verificationURI string) (oauth2.DeviceCode, error)) *Service_CreateDeviceCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeviceCodeByUserCode provides a mock function for the type Service
func (_mock *Service) GetDeviceCodeByUserCode(ctx context.Context, userCode string) (oauth2.DeviceCode, error) {
	ret := _mock.Called(ctx, userCode)

	if len(ret) == 0 {
		panic("no return value specified for GetDeviceCodeByUserCode")
	}

	var r0 oauth2.DeviceCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (oauth2.DeviceCode, error)); ok {
		return returnFunc(ctx, userCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) oauth2.DeviceCode); ok {
		r0 = returnFunc(ctx, userCode)
	} else {
		r0 = ret.Get(0).(oauth2.DeviceCode)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetDeviceCodeByUserCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeviceCodeByUserCode'
type Service_GetDeviceCodeByUserCode_Call struct {
	*mock.Call
}

// GetDeviceCodeByUserCode is a helper method to define mock.On call
//   - ctx context.Context
//   - userCode string
func (_e *Service_Expecter) GetDeviceCodeByUserCode(ctx interface{}, userCode interface{}) *Service_GetDeviceCodeByUserCode_Call {
	return &Service_GetDeviceCodeByUserCode_Call{Call: _e.mock.On("GetDeviceCodeByUserCode", ctx, userCode)}
}

func (_c *Service_GetDeviceCodeByUserCode_Call) Run(run func(ctx context.Context, userCode string)) *Service_GetDeviceCodeByUserCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_GetDeviceCodeByUserCode_Call) Return(deviceCode oauth2.DeviceCode, err error) *Service_GetDeviceCodeByUserCode_Call {
	_c.Call.Return(deviceCode, err)
	return _c
}

func (_c *Service_GetDeviceCodeByUserCode_Call) RunAndReturn(run func(ctx context.Context, userCode string) (oauth2.DeviceCode, error)) *Service_GetDeviceCodeByUserCode_Call {
	_c.Call.Return(run)
	return _c
}

// PollDeviceToken provides a mock function for the type Service
func (_mock *Service) PollDeviceToken(ctx context.Context, provider oauth2.Provider, deviceCode string) (*v1.Token, error) {
	ret := _mock.Called(ctx, provider, deviceCode)

	if len(ret) == 0 {
		panic("no return value specified for PollDeviceToken")
	}

	var r0 *v1.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth2.Provider, string) (*v1.Token, error)); ok {
		return returnFunc(ctx, provider, deviceCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth2.Provider, string) *v1.Token); ok {
		r0 = returnFunc(ctx, provider, deviceCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oauth2.Provider, string) error); ok {
		r1 = returnFunc(ctx, provider, deviceCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_PollDeviceToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollDeviceToken'
type Service_PollDeviceToken_Call struct {
	*mock.Call
}

// PollDeviceToken is a helper method to define mock.On call
//   - ctx context.Context
//   - provider oauth2.Provider
//   - deviceCode string
func (_e *Service_Expecter) PollDeviceToken(ctx interface{}, provider interface{}, deviceCode interface{}) *Service_PollDeviceToken_Call {
	return &Service_PollDeviceToken_Call{Call: _e.mock.On("PollDeviceToken", ctx, provider, deviceCode)}
}

func (_c *Service_PollDeviceToken_Call) Run(run func(ctx context.Context, provider oauth2.Provider, deviceCode string)) *Service_PollDeviceToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oauth2.Provider
		if args[1] != nil {
			arg1 = args[1].(oauth2.Provider)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_PollDeviceToken_Call) Return(token *v1.Token, err error) *Service_PollDeviceToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *Service_PollDeviceToken_Call) RunAndReturn(run func(ctx context.Context, provider oauth2.Provider, deviceCode string) (*v1.Token, error)) *Service_PollDeviceToken_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessDeviceCallback provides a mock function for the type Service
func (_mock *Service) ProcessDeviceCallback(ctx context.Context, provider oauth2.Provider, userCode string, oauthCode string) error {
	ret := _mock.Called(ctx, provider, userCode, oauthCode)

	if len(ret) == 0 {
		panic("no return value specified for ProcessDeviceCallback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth2.Provider, string, string) error); ok {
		r0 = returnFunc(ctx, provider, userCode, oauthCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_ProcessDeviceCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessDeviceCallback'
type Service_ProcessDeviceCallback_Call struct {
	*mock.Call
}

// ProcessDeviceCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - provider oauth2.Provider
//   - userCode string
//   - oauthCode string
func (_e *Service_Expecter) ProcessDeviceCallback(ctx interface{}, provider interface{}, userCode interface{}, oauthCode interface{}) *Service_ProcessDeviceCallback_Call {
	return &Service_ProcessDeviceCallback_Call{Call: _e.mock.On("ProcessDeviceCallback", ctx, provider, userCode, oauthCode)}
}

func (_c *Service_ProcessDeviceCallback_Call) Run(run func(ctx context.Context, provider oauth2.Provider, userCode string, oauthCode string)) *Service_ProcessDeviceCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oauth2.Provider
		if args[1] != nil {
			arg1 = args[1].(oauth2.Provider)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Service_ProcessDeviceCallback_Call) Return(err error) *Service_ProcessDeviceCallback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_ProcessDeviceCallback_Call) RunAndReturn(run func(ctx context.Context, provider oauth2.Provider, userCode string, oauthCode string) error) *Service_ProcessDeviceCallback_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessWebCallback provides a mock function for the type Service
func (_mock *Service) ProcessWebCallback(ctx context.Context, provider oauth2.Provider, code string, redirectURL string) (*v1.Token, error) {
	ret := _mock.Called(ctx, provider, code, redirectURL)

	if len(ret) == 0 {
		panic("no return value specified for ProcessWebCallback")
	}

	var r0 *v1.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth2.Provider, string, string) (*v1.Token, error)); ok {
		return returnFunc(ctx, provider, code, redirectURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth2.Provider, string, string) *v1.Token); ok {
		r0 = returnFunc(ctx, provider, code, redirectURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oauth2.Provider, string, string) error); ok {
		r1 = returnFunc(ctx, provider, code, redirectURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_ProcessWebCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessWebCallback'
type Service_ProcessWebCallback_Call struct {
	*mock.Call
}

// ProcessWebCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - provider oauth2.Provider
//   - code string
//   - redirectURL string
func (_e *Service_Expecter) ProcessWebCallback(ctx interface{}, provider interface{}, code interface{}, redirectURL interface{}) *Service_ProcessWebCallback_Call {
	return &Service_ProcessWebCallback_Call{Call: _e.mock.On("ProcessWebCallback", ctx, provider, code, redirectURL)}
}

func (_c *Service_ProcessWebCallback_Call) Run(run func(ctx context.Context, provider oauth2.Provider, code string, redirectURL string)) *Service_ProcessWebCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oauth2.Provider
		if args[1] != nil {
			arg1 = args[1].(oauth2.Provider)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Service_ProcessWebCallback_Call) Return(token *v1.Token, err error) *Service_ProcessWebCallback_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *Service_ProcessWebCallback_Call) RunAndReturn(run func(ctx context.Context, provider oauth2.Provider, code string, redirectURL string) (*v1.Token, error)) *Service_ProcessWebCallback_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyDevice provides a mock function for the type Service
func (_mock *Service) VerifyDevice(ctx context.Context, provider oauth2.Provider, userCode string, oauthCode string, approve bool) error {
	ret := _mock.Called(ctx, provider, userCode, oauthCode, approve)

	if len(ret) == 0 {
		panic("no return value specified for VerifyDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth2.Provider, string, string, bool) error); ok {
		r0 = returnFunc(ctx, provider, userCode, oauthCode, approve)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_VerifyDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyDevice'
type Service_VerifyDevice_Call struct {
	*mock.Call
}

// VerifyDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - provider oauth2.Provider
//   - userCode string
//   - oauthCode string
//   - approve bool
func (_e *Service_Expecter) VerifyDevice(ctx interface{}, provider interface{}, userCode interface{}, oauthCode interface{}, approve interface{}) *Service_VerifyDevice_Call {
	return &Service_VerifyDevice_Call{Call: _e.mock.On("VerifyDevice", ctx, provider, userCode, oauthCode, approve)}
}

func (_c *Service_VerifyDevice_Call) Run(run func(ctx context.Context, provider oauth2.Provider, userCode string, oauthCode string, approve bool)) *Service_VerifyDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oauth2.Provider
		if args[1] != nil {
			arg1 = args[1].(oauth2.Provider)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Service_VerifyDevice_Call) Return(err error) *Service_VerifyDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_VerifyDevice_Call) RunAndReturn(run func(ctx context.Context, provider oauth2.Provider, userCode string, oauthCode string, approve bool) error) *Service_VerifyDevice_Call {
	_c.Call.Return(run)
	return _c
}
